### PR TITLE
CAN-1097

### PR DESCRIPTION
**Pull request by vikasranatalentelgia**
Implement API to fetch support tree under a topic in frontend
test cases fixed
upload file persistence

### CODE REVIEW

**Review by akuks — APPROVED** [review]

**Comment by akuks** [comment]
@vikasranatalentelgia please fix the conflicts

**Comment by vikasranatalentelgia** [comment]
> @vikasranatalentelgia please fix the conflicts

Fixed. Please check

**Comment by akuks** [comment]
Can you please resolve the conflicts

**Comment by vikasranatalentelgia** [comment]
> Can you please resolve the conflicts

resolved.

**Pull request merged**
