### PR TITLE
Can 1129 & Can 1156

### PR DESCRIPTION
**Pull request by shahab-ramzan**
Added subscription status against every camp in the tree  and updated custom hook to get userID as well

### CODE REVIEW

**Review by akuks — CHANGES_REQUESTED** [review]
`src/components/ComponentPages/TopicDetails/SupportTreeCard/.index.tsx.swp` Please remove this file. It is not required

**Comment by akuks** [comment]
This also needs to be modified in the unit test cases

**Comment by shahab-ramzan** [comment]
> `src/components/ComponentPages/TopicDetails/SupportTreeCard/.index.tsx.swp` Please remove this file. It is not required

@akuks removed

**Comment by shahab-ramzan** [comment]
> This also needs to be modified in the unit test cases

Done

**Review by akuks — APPROVED** [review]

**Pull request merged**
