### PR TITLE
Test cases

### PR DESCRIPTION
**Pull request by vikasranatalentelgia**

### CODE REVIEW

**Comment by shahab-ramzan** [comment]
@vikasranatalentelgia Can you please verify PR. This branch contains 273 commits.

**Comment by shahab-ramzan** [comment]
@vikasranatalentelgia I can't merge this branch since it contains 274 commits unless  justification of these commits can be provided.

**Comment by akuks** [comment]
@vikasranatalentelgia as discussed please delete the .env.bkp

**Comment by vikasranatalentelgia** [comment]
> @vikasranatalentelgia as discussed please delete the .env.bkp

@akuks it is deleted

**Pull request merged**
