### PR TITLE
Can issue 564

### PR DESCRIPTION
**Pull request by shahab-ramzan**
Meta Tags added

### CODE REVIEW

**Review by gautamv16 — APPROVED** [review]

**Review by gautamv16 — CHANGES_REQUESTED** [review]
PLease resolve conflicts

**Comment by shahab-ramzan** [comment]
> PLease resolve conflicts

Resolved

**Review by gautamv16 — APPROVED** [review]

**Review by gautamv16 — CHANGES_REQUESTED** [review]
Please resolve conflicts

**Comment by shahab-ramzan** [comment]
> Please resolve conflicts

Resolved

**Review by gautamv16 — APPROVED** [review]

**Pull request merged**
